# Generated by Django 3.1.2 on 2020-10-19 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_customer_invoice_invoicelineitem_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='invoicelineitem',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'managed': True},
        ),
    ]
