# Generated by Django 3.1.2 on 2020-10-19 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_auto_20201019_0940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='invoicelineitem',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'managed': False},
        ),
    ]
